config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :educations
  resources :interests
  resources :projects
  resources :works

    root to: "interests#index"
  end

  root 'home#index'
  get 'resume', to: 'home#resume', as: 'resume'
end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/educations_controller.rb
module Admin
  class EducationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Education.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Education.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/hobbies_controller.rb
module Admin
  class HobbiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Hobby.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Hobby.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/interests_controller.rb
module Admin
  class InterestsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Interest.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Interest.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/works_controller.rb
module Admin
  class WorksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Work.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Work.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def resume
    @interests = Interest.all.order(:rank)
    @projects = Project.all.order(:rank)
    @education = Education.all
    @work = Work.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Colin Anderson
.row
  %h2 About me
  = react_component 'AboutMe'


.div
  = link_to 'Resume', resume_path

app/views/home/resume.html.haml
.container
  .row.valign-wrapper
    .col.s6
      %h4 Colin Anderson
      %span 6427 Ralph H Circle
      %br
      %span Herriman, UT 84096
    .col.s3.offset-s3.right-align.card.contact-me.blue.lighten-1.grey-text
      %span.card-title Contact Info
      %a.link{href: 'mailto:andercol.4@gmail.com'}
        andercol.4@gmail.com
      %br
      %a.link{href: 'https://linkedin.com/in/andercol4'}
        Linkedin: andercol4
      %br
      %a.link{href: 'https://github.com/andercol4'}
        Github: andercol4
      %br
      %span Phone: (801)231-3321
  .row
    .col.s12
      .card
        %h5.s12
          Interests
        %ul
          - @interests.each do |interest|
            %li
              .chip
                = interest.name
    .col.m12
      .card
        .row
          .col.s11.offset-s1
            %h3.blue-text Experience
          - @projects.each do |project|
            .col.s10.offset-s1
              .row.valign-wrapper
                .col.s4
                  %h5.left-align.blue-text
                    = project.name
                .col.s8
                  %p.valign.right-align.blue-text
                    = "#{project.start_date}-#{project.end_date}"
              .row
                .col.s12
                  %span.description
                    = project.description
              .row
                .col.s6
                  %a{href: project.url, target: 'blank_'}
                    = project.url
                .col.s6.right-align
                  %a{href: project.git_repo, target: 'blank_'}
                    = project.git_repo
          .col.s10.offset-s1
            - @education.each do |education|
              .col.s6
                %h5.left-align.blue-text
                  = education.name
              .col.s6
                %p.right-align.blue-text
                  = "#{education.start_date}-#{education.end_date}"
              .col.s12
                %span.description
                  = education.description
            - @work.each do |work|
              .col.s8
                %h5.left-align.blue-text
                  = work.title
              .col.s4
                %p.right-align.blue-text
                  = "#{work.start_date}-#{work.end_date}"
              .col.s12
              %span.description
                = work.description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PortfolioSite
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield